version: '3'
services:
  my-app:
    container_name: spring-boot-application
    image: univer-task
    hostname: roma
    ports:
      - "9000:8080"
    expose:
      - "8080"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    hostname: prometheus_univer
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/config.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/config.yml
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"