global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'actuator'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8080']