management:
  endpoints:
    web:
      exposure:
        include: health,prometheus, testOK, testClientError, testServerError, test1
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
